version: '3.8'

services:
  app:
    build: .
    container_name: auth-users-api
    ports:
      - "3000:3000"
    env_file:
      - .env # 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    restart: always